app = "terraxinyun-labs"
primary_region = "sin"

[build]

[env]
  PASSWORD = "terraxinyun"

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
